
//Set path to SmartSlog KP Library
#pragma clang diagnostic push
#pragma ide diagnostic ignored "CannotResolve"
#include <smartslog.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT 1
#define INCLUDE_PROPERTY_TAKEDRUGTIME 1
#define INCLUDE_PROPERTY_USEEQUIPMENTTIME 1
#define INCLUDE_PROPERTY_USERNAME 1
#define INCLUDE_PROPERTY_ISONLINE 1
#define INCLUDE_PROPERTY_FREEPATIENTCAPACITY 1
#define INCLUDE_PROPERTY_HASDRUGTOSAVE 1
#define INCLUDE_PROPERTY_EQUIPPARAMETER 1
#define INCLUDE_PROPERTY_IMG 1
#define INCLUDE_PROPERTY_HOSPITALNAME 1
#define INCLUDE_PROPERTY_HASDOCTOR 1
#define INCLUDE_PROPERTY_CARNUMBER 1
#define INCLUDE_PROPERTY_SENDALARM 1
#define INCLUDE_PROPERTY_HASDRUGTOMEDICINE 1
#define INCLUDE_PROPERTY_ADVICETEXT 1
#define INCLUDE_PROPERTY_HASDRUGTOTAKE 1
#define INCLUDE_PROPERTY_DRUGNAME 1
#define INCLUDE_PROPERTY_SENDADVICE 1
#define INCLUDE_PROPERTY_AGE 1
#define INCLUDE_PROPERTY_DRUGANNOTATION 1
#define INCLUDE_PROPERTY_ALARMSTATUS 1
#define INCLUDE_PROPERTY_PHARMNAME 1
#define INCLUDE_PROPERTY_HASPERSLOCATION 1
#define INCLUDE_PROPERTY_HASAMBLOCATION 1
#define INCLUDE_PROPERTY_HASDRUGTOSALE 1
#define INCLUDE_PROPERTY_WORKHOSPITAL 1
#define INCLUDE_PROPERTY_ALARMTIME 1
#define INCLUDE_PROPERTY_HASHOSPLOCATION 1
#define INCLUDE_PROPERTY_PHONE 1
#define INCLUDE_PROPERTY_HASPHARMLOCATION 1
#define INCLUDE_PROPERTY_DOSAGE 1
#define INCLUDE_PROPERTY_LONG 1
#define INCLUDE_PROPERTY_LAT 1
#define INCLUDE_PROPERTY_PERSONINFORMATION 1
#define INCLUDE_PROPERTY_PASSWORD 1
#define INCLUDE_PROPERTY_MBOX 1
#define INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT 1
#define INCLUDE_PROPERTY_WORKAMBULANCE 1
#define INCLUDE_PROPERTY_NAME 1
#define INCLUDE_PROPERTY_ADVICETIME 1
#define INCLUDE_CLASS_DOCTOR 1
#define INCLUDE_CLASS_CARING 1
#define INCLUDE_CLASS_HOSPITAL 1
#define INCLUDE_CLASS_NURSE 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_PHARMACY 1
#define INCLUDE_CLASS_PROFILE 1
#define INCLUDE_CLASS_LOCATION 1
#define INCLUDE_CLASS_ALARM 1
#define INCLUDE_CLASS_BED 1
#define INCLUDE_CLASS_PATIENT 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_EQUIPMENT 1
#define INCLUDE_CLASS_ADVICE 1
#define INCLUDE_CLASS_DRUG 1
#define INCLUDE_CLASS_AMBULANCE 1
#define INCLUDE_CLASS_MEDIC 1
#define INCLUDE_CLASS_NOTHING 1


#else

#define INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT 0
#define INCLUDE_PROPERTY_TAKEDRUGTIME 0
#define INCLUDE_PROPERTY_USEEQUIPMENTTIME 0
#define INCLUDE_PROPERTY_USERNAME 0
#define INCLUDE_PROPERTY_ISONLINE 0
#define INCLUDE_PROPERTY_FREEPATIENTCAPACITY 0
#define INCLUDE_PROPERTY_HASDRUGTOSAVE 0
#define INCLUDE_PROPERTY_EQUIPPARAMETER 0
#define INCLUDE_PROPERTY_IMG 0
#define INCLUDE_PROPERTY_HOSPITALNAME 0
#define INCLUDE_PROPERTY_HASDOCTOR 0
#define INCLUDE_PROPERTY_CARNUMBER 0
#define INCLUDE_PROPERTY_SENDALARM 0
#define INCLUDE_PROPERTY_HASDRUGTOMEDICINE 0
#define INCLUDE_PROPERTY_ADVICETEXT 0
#define INCLUDE_PROPERTY_HASDRUGTOTAKE 0
#define INCLUDE_PROPERTY_DRUGNAME 0
#define INCLUDE_PROPERTY_SENDADVICE 0
#define INCLUDE_PROPERTY_AGE 0
#define INCLUDE_PROPERTY_DRUGANNOTATION 0
#define INCLUDE_PROPERTY_ALARMSTATUS 0
#define INCLUDE_PROPERTY_PHARMNAME 0
#define INCLUDE_PROPERTY_HASPERSLOCATION 0
#define INCLUDE_PROPERTY_HASAMBLOCATION 0
#define INCLUDE_PROPERTY_HASDRUGTOSALE 0
#define INCLUDE_PROPERTY_WORKHOSPITAL 0
#define INCLUDE_PROPERTY_ALARMTIME 0
#define INCLUDE_PROPERTY_HASHOSPLOCATION 0
#define INCLUDE_PROPERTY_PHONE 0
#define INCLUDE_PROPERTY_HASPHARMLOCATION 0
#define INCLUDE_PROPERTY_DOSAGE 0
#define INCLUDE_PROPERTY_LONG 0
#define INCLUDE_PROPERTY_LAT 0
#define INCLUDE_PROPERTY_PERSONINFORMATION 0
#define INCLUDE_PROPERTY_PASSWORD 0
#define INCLUDE_PROPERTY_MBOX 0
#define INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT 0
#define INCLUDE_PROPERTY_WORKAMBULANCE 0
#define INCLUDE_PROPERTY_NAME 0
#define INCLUDE_PROPERTY_ADVICETIME 0
#define INCLUDE_CLASS_DOCTOR 0
#define INCLUDE_CLASS_CARING 0
#define INCLUDE_CLASS_HOSPITAL 0
#define INCLUDE_CLASS_NURSE 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_PHARMACY 0
#define INCLUDE_CLASS_PROFILE 0
#define INCLUDE_CLASS_LOCATION 0
#define INCLUDE_CLASS_ALARM 0
#define INCLUDE_CLASS_BED 0
#define INCLUDE_CLASS_PATIENT 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_EQUIPMENT 0
#define INCLUDE_CLASS_ADVICE 0
#define INCLUDE_CLASS_DRUG 0
#define INCLUDE_CLASS_AMBULANCE 0
#define INCLUDE_CLASS_MEDIC 0
#define INCLUDE_CLASS_NOTHING 0


#endif


#if INCLUDE_CLASS_DOCTOR
extern sslog_class_t *CLASS_DOCTOR;
#endif
#if INCLUDE_CLASS_CARING
extern sslog_class_t *CLASS_CARING;
#endif
#if INCLUDE_CLASS_HOSPITAL
extern sslog_class_t *CLASS_HOSPITAL;
#endif
#if INCLUDE_CLASS_NURSE
extern sslog_class_t *CLASS_NURSE;
#endif
#if INCLUDE_CLASS_PERSON
extern sslog_class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_PHARMACY
extern sslog_class_t *CLASS_PHARMACY;
#endif
#if INCLUDE_CLASS_PROFILE
extern sslog_class_t *CLASS_PROFILE;
#endif
#if INCLUDE_CLASS_LOCATION
extern sslog_class_t *CLASS_LOCATION;
#endif
#if INCLUDE_CLASS_ALARM
extern sslog_class_t *CLASS_ALARM;
#endif
#if INCLUDE_CLASS_BED
extern sslog_class_t *CLASS_BED;
#endif
#if INCLUDE_CLASS_PATIENT
extern sslog_class_t *CLASS_PATIENT;
#endif
#if INCLUDE_CLASS_THING
extern sslog_class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_EQUIPMENT
extern sslog_class_t *CLASS_EQUIPMENT;
#endif
#if INCLUDE_CLASS_ADVICE
extern sslog_class_t *CLASS_ADVICE;
#endif
#if INCLUDE_CLASS_DRUG
extern sslog_class_t *CLASS_DRUG;
#endif
#if INCLUDE_CLASS_AMBULANCE
extern sslog_class_t *CLASS_AMBULANCE;
#endif
#if INCLUDE_CLASS_MEDIC
extern sslog_class_t *CLASS_MEDIC;
#endif
#if INCLUDE_CLASS_NOTHING
extern sslog_class_t *CLASS_NOTHING;
#endif


#if INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT
extern sslog_property_t *PROPERTY_HASSTATIONAREQUIPMENT;
#endif
#if INCLUDE_PROPERTY_TAKEDRUGTIME
extern sslog_property_t *PROPERTY_TAKEDRUGTIME;
#endif
#if INCLUDE_PROPERTY_USEEQUIPMENTTIME
extern sslog_property_t *PROPERTY_USEEQUIPMENTTIME;
#endif
#if INCLUDE_PROPERTY_USERNAME
extern sslog_property_t *PROPERTY_USERNAME;
#endif
#if INCLUDE_PROPERTY_ISONLINE
extern sslog_property_t *PROPERTY_ISONLINE;
#endif
#if INCLUDE_PROPERTY_FREEPATIENTCAPACITY
extern sslog_property_t *PROPERTY_FREEPATIENTCAPACITY;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOSAVE
extern sslog_property_t *PROPERTY_HASDRUGTOSAVE;
#endif
#if INCLUDE_PROPERTY_EQUIPPARAMETER
extern sslog_property_t *PROPERTY_EQUIPPARAMETER;
#endif
#if INCLUDE_PROPERTY_IMG
extern sslog_property_t *PROPERTY_IMG;
#endif
#if INCLUDE_PROPERTY_HOSPITALNAME
extern sslog_property_t *PROPERTY_HOSPITALNAME;
#endif
#if INCLUDE_PROPERTY_HASDOCTOR
extern sslog_property_t *PROPERTY_HASDOCTOR;
#endif
#if INCLUDE_PROPERTY_CARNUMBER
extern sslog_property_t *PROPERTY_CARNUMBER;
#endif
#if INCLUDE_PROPERTY_SENDALARM
extern sslog_property_t *PROPERTY_SENDALARM;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOMEDICINE
extern sslog_property_t *PROPERTY_HASDRUGTOMEDICINE;
#endif
#if INCLUDE_PROPERTY_ADVICETEXT
extern sslog_property_t *PROPERTY_ADVICETEXT;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOTAKE
extern sslog_property_t *PROPERTY_HASDRUGTOTAKE;
#endif
#if INCLUDE_PROPERTY_DRUGNAME
extern sslog_property_t *PROPERTY_DRUGNAME;
#endif
#if INCLUDE_PROPERTY_SENDADVICE
extern sslog_property_t *PROPERTY_SENDADVICE;
#endif
#if INCLUDE_PROPERTY_AGE
extern sslog_property_t *PROPERTY_AGE;
#endif
#if INCLUDE_PROPERTY_DRUGANNOTATION
extern sslog_property_t *PROPERTY_DRUGANNOTATION;
#endif
#if INCLUDE_PROPERTY_ALARMSTATUS
extern sslog_property_t *PROPERTY_ALARMSTATUS;
#endif
#if INCLUDE_PROPERTY_PHARMNAME
extern sslog_property_t *PROPERTY_PHARMNAME;
#endif
#if INCLUDE_PROPERTY_HASPERSLOCATION
extern sslog_property_t *PROPERTY_HASPERSLOCATION;
#endif
#if INCLUDE_PROPERTY_HASAMBLOCATION
extern sslog_property_t *PROPERTY_HASAMBLOCATION;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOSALE
extern sslog_property_t *PROPERTY_HASDRUGTOSALE;
#endif
#if INCLUDE_PROPERTY_WORKHOSPITAL
extern sslog_property_t *PROPERTY_WORKHOSPITAL;
#endif
#if INCLUDE_PROPERTY_ALARMTIME
extern sslog_property_t *PROPERTY_ALARMTIME;
#endif
#if INCLUDE_PROPERTY_HASHOSPLOCATION
extern sslog_property_t *PROPERTY_HASHOSPLOCATION;
#endif
#if INCLUDE_PROPERTY_PHONE
extern sslog_property_t *PROPERTY_PHONE;
#endif
#if INCLUDE_PROPERTY_HASPHARMLOCATION
extern sslog_property_t *PROPERTY_HASPHARMLOCATION;
#endif
#if INCLUDE_PROPERTY_DOSAGE
extern sslog_property_t *PROPERTY_DOSAGE;
#endif
#if INCLUDE_PROPERTY_LONG
extern sslog_property_t *PROPERTY_LONG;
#endif
#if INCLUDE_PROPERTY_LAT
extern sslog_property_t *PROPERTY_LAT;
#endif
#if INCLUDE_PROPERTY_PERSONINFORMATION
extern sslog_property_t *PROPERTY_PERSONINFORMATION;
#endif
#if INCLUDE_PROPERTY_PASSWORD
extern sslog_property_t *PROPERTY_PASSWORD;
#endif
#if INCLUDE_PROPERTY_MBOX
extern sslog_property_t *PROPERTY_MBOX;
#endif
#if INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT
extern sslog_property_t *PROPERTY_HASPORTABLEEQUIPMENT;
#endif
#if INCLUDE_PROPERTY_WORKAMBULANCE
extern sslog_property_t *PROPERTY_WORKAMBULANCE;
#endif
#if INCLUDE_PROPERTY_NAME
extern sslog_property_t *PROPERTY_NAME;
#endif
#if INCLUDE_PROPERTY_ADVICETIME
extern sslog_property_t *PROPERTY_ADVICETIME;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */

#pragma clang diagnostic pop