
//Set path to SmartSlog KP Library
#include <smartslog.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_HASTHEARTRHYTHM 1
#define INCLUDE_PROPERTY_VENTICULARRYTHM 1
#define INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT 1
#define INCLUDE_PROPERTY_TAKEDRUGTIME 1
#define INCLUDE_PROPERTY_HASPATIENTMAP 1
#define INCLUDE_PROPERTY_RESPONSETOALARM 1
#define INCLUDE_PROPERTY_ISPATIENTDRUGADDICTED 1
#define INCLUDE_PROPERTY_STARTWAVECOMP 1
#define INCLUDE_PROPERTY_USEEQUIPMENTTIME 1
#define INCLUDE_PROPERTY_USERNAME 1
#define INCLUDE_PROPERTY_ISONLINE 1
#define INCLUDE_PROPERTY_HASCRITERIA 1
#define INCLUDE_PROPERTY_FREEPATIENTCAPACITY 1
#define INCLUDE_PROPERTY_HASDRUGTOSAVE 1
#define INCLUDE_PROPERTY_EQUIPPARAMETER 1
#define INCLUDE_PROPERTY_PATIENTWEIGHT 1
#define INCLUDE_PROPERTY_READYTOHELP 1
#define INCLUDE_PROPERTY_IMG 1
#define INCLUDE_PROPERTY_PASSAUTH 1
#define INCLUDE_PROPERTY_HOSPITALNAME 1
#define INCLUDE_PROPERTY_HASDOCTOR 1
#define INCLUDE_PROPERTY_CARNUMBER 1
#define INCLUDE_PROPERTY_HASQRSCOMPLEX 1
#define INCLUDE_PROPERTY_ECGDATAURL 1
#define INCLUDE_PROPERTY_HASMEASURMENT 1
#define INCLUDE_PROPERTY_SENDALARM 1
#define INCLUDE_PROPERTY_HASDRUGTOMEDICINE 1
#define INCLUDE_PROPERTY_SPECIALLITY 1
#define INCLUDE_PROPERTY_ADVICETEXT 1
#define INCLUDE_PROPERTY_XPOINT 1
#define INCLUDE_PROPERTY_HASYAXIS 1
#define INCLUDE_PROPERTY_HASDRUGTOTAKE 1
#define INCLUDE_PROPERTY_HASMEDICALRECORDSCARD 1
#define INCLUDE_PROPERTY_HASACCESS 1
#define INCLUDE_PROPERTY_VENTICULARRATE 1
#define INCLUDE_PROPERTY_CONTAINECGSURVEYS 1
#define INCLUDE_PROPERTY_DRUGNAME 1
#define INCLUDE_PROPERTY_SENDADVICE 1
#define INCLUDE_PROPERTY_HASPWAVE 1
#define INCLUDE_PROPERTY_HASDOCUMENT 1
#define INCLUDE_PROPERTY_ISPATIENTMEDICINEADDICTED 1
#define INCLUDE_PROPERTY_SERVEYDATE 1
#define INCLUDE_PROPERTY_DATAVALUE 1
#define INCLUDE_PROPERTY_LEADDESCRIPTION 1
#define INCLUDE_PROPERTY_AGE 1
#define INCLUDE_PROPERTY_ALARMSTATUS 1
#define INCLUDE_PROPERTY_DRUGANNOTATION 1
#define INCLUDE_PROPERTY_PATIENTBLOODTYPE 1
#define INCLUDE_PROPERTY_PHARMNAME 1
#define INCLUDE_PROPERTY_ATRIALRYTHM 1
#define INCLUDE_PROPERTY_HASPERSLOCATION 1
#define INCLUDE_PROPERTY_PATIENTRHFACTOR 1
#define INCLUDE_PROPERTY_SURVEYECGINFO 1
#define INCLUDE_PROPERTY_CONTAINUSHSURVEYS 1
#define INCLUDE_PROPERTY_HASAMBLOCATION 1
#define INCLUDE_PROPERTY_DISEASEDESCRIPTION 1
#define INCLUDE_PROPERTY_HASDRUGTOSALE 1
#define INCLUDE_PROPERTY_SERVEYRESULT 1
#define INCLUDE_PROPERTY_PATIENTHEIGHT 1
#define INCLUDE_PROPERTY_HASLEAD 1
#define INCLUDE_PROPERTY_WORKHOSPITAL 1
#define INCLUDE_PROPERTY_ALARMTIME 1
#define INCLUDE_PROPERTY_PHONE 1
#define INCLUDE_PROPERTY_HASHOSPLOCATION 1
#define INCLUDE_PROPERTY_STARTTIME 1
#define INCLUDE_PROPERTY_HASHEARTRATE 1
#define INCLUDE_PROPERTY_HASTWAVE 1
#define INCLUDE_PROPERTY_MEASURMENTDESCRIPTION 1
#define INCLUDE_PROPERTY_HASPHARMLOCATION 1
#define INCLUDE_PROPERTY_MEASURMENTVALUE 1
#define INCLUDE_PROPERTY_SERVEYDATALINK 1
#define INCLUDE_PROPERTY_HASANOMALY 1
#define INCLUDE_PROPERTY_INTERVALSCALE 1
#define INCLUDE_PROPERTY_ISPATIENTSMOKE 1
#define INCLUDE_PROPERTY_HASXAXIS 1
#define INCLUDE_PROPERTY_HASPATIENTMETRICS 1
#define INCLUDE_PROPERTY_ENDWAVECOMP 1
#define INCLUDE_PROPERTY_DOSAGE 1
#define INCLUDE_PROPERTY_SERVEYTYPE 1
#define INCLUDE_PROPERTY_DOCUMENTNUMBERFULL 1
#define INCLUDE_PROPERTY_PEAK 1
#define INCLUDE_PROPERTY_LONG 1
#define INCLUDE_PROPERTY_ISPATIENTALCOHOLADDICTED 1
#define INCLUDE_PROPERTY_SERVEYDESCRIPTION 1
#define INCLUDE_PROPERTY_DOCUMENTTYPE 1
#define INCLUDE_PROPERTY_HASDIAGNOSIS 1
#define INCLUDE_PROPERTY_LAT 1
#define INCLUDE_PROPERTY_SURNAME 1
#define INCLUDE_PROPERTY_DOCUMENTRELEASEDATE 1
#define INCLUDE_PROPERTY_AUTHREQUESTSTATUS 1
#define INCLUDE_PROPERTY_PERSONINFORMATION 1
#define INCLUDE_PROPERTY_PASSWORD 1
#define INCLUDE_PROPERTY_MBOX 1
#define INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT 1
#define INCLUDE_PROPERTY_ATRIALRATE 1
#define INCLUDE_PROPERTY_WORKAMBULANCE 1
#define INCLUDE_PROPERTY_NAME 1
#define INCLUDE_PROPERTY_ENDTIME 1
#define INCLUDE_PROPERTY_ADVICETIME 1
#define INCLUDE_PROPERTY_HASWAVEFORMSTRUCTURE 1
#define INCLUDE_PROPERTY_HASWAVECOMPONENT 1
#define INCLUDE_PROPERTY_DISEASETYPE 1
#define INCLUDE_PROPERTY_SERVEYUSHINFO 1
#define INCLUDE_PROPERTY_CONTAINDISEASES 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_ALARM 1
#define INCLUDE_CLASS_DOCTOR 1
#define INCLUDE_CLASS_NURSE 1
#define INCLUDE_CLASS_ECGTWAVE 1
#define INCLUDE_CLASS_ECGDIAGNOSIS 1
#define INCLUDE_CLASS_LOCATION 1
#define INCLUDE_CLASS_ECGWAVECOMPONENT 1
#define INCLUDE_CLASS_ECGDATA 1
#define INCLUDE_CLASS_ADVICE 1
#define INCLUDE_CLASS_PATIENTMETRICS 1
#define INCLUDE_CLASS_MEDICALRECORDSCARD 1
#define INCLUDE_CLASS_PHARMACY 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_HOSPITAL 1
#define INCLUDE_CLASS_MEASURMENT 1
#define INCLUDE_CLASS_RHYTHM 1
#define INCLUDE_CLASS_PROFILE 1
#define INCLUDE_CLASS_SERVEY 1
#define INCLUDE_CLASS_DISEASE 1
#define INCLUDE_CLASS_ECGSERVEY 1
#define INCLUDE_CLASS_DOCUMENT 1
#define INCLUDE_CLASS_BED 1
#define INCLUDE_CLASS_ECGLEAD 1
#define INCLUDE_CLASS_ECGQRSCOMPLEX 1
#define INCLUDE_CLASS_PATIENTMAP 1
#define INCLUDE_CLASS_MEDIC 1
#define INCLUDE_CLASS_ANOMALY 1
#define INCLUDE_CLASS_USHSERVEY 1
#define INCLUDE_CLASS_CARING 1
#define INCLUDE_CLASS_AMBULANCE 1
#define INCLUDE_CLASS_CRITERIA 1
#define INCLUDE_CLASS_WAVEFORMSTRUCTURE 1
#define INCLUDE_CLASS_EQUIPMENT 1
#define INCLUDE_CLASS_DRUG 1
#define INCLUDE_CLASS_HEARTRATE 1
#define INCLUDE_CLASS_ECGXAXIS 1
#define INCLUDE_CLASS_ECGPWAVE 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_PATIENT 1
#define INCLUDE_CLASS_ECGYAXIS 1
#define INCLUDE_CLASS_AUTHREQUEST 1


#else

#define INCLUDE_PROPERTY_HASTHEARTRHYTHM 0
#define INCLUDE_PROPERTY_VENTICULARRYTHM 0
#define INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT 0
#define INCLUDE_PROPERTY_TAKEDRUGTIME 0
#define INCLUDE_PROPERTY_HASPATIENTMAP 0
#define INCLUDE_PROPERTY_RESPONSETOALARM 0
#define INCLUDE_PROPERTY_ISPATIENTDRUGADDICTED 0
#define INCLUDE_PROPERTY_STARTWAVECOMP 0
#define INCLUDE_PROPERTY_USEEQUIPMENTTIME 0
#define INCLUDE_PROPERTY_USERNAME 0
#define INCLUDE_PROPERTY_ISONLINE 0
#define INCLUDE_PROPERTY_HASCRITERIA 0
#define INCLUDE_PROPERTY_FREEPATIENTCAPACITY 0
#define INCLUDE_PROPERTY_HASDRUGTOSAVE 0
#define INCLUDE_PROPERTY_EQUIPPARAMETER 0
#define INCLUDE_PROPERTY_PATIENTWEIGHT 0
#define INCLUDE_PROPERTY_READYTOHELP 0
#define INCLUDE_PROPERTY_IMG 0
#define INCLUDE_PROPERTY_PASSAUTH 0
#define INCLUDE_PROPERTY_HOSPITALNAME 0
#define INCLUDE_PROPERTY_HASDOCTOR 0
#define INCLUDE_PROPERTY_CARNUMBER 0
#define INCLUDE_PROPERTY_HASQRSCOMPLEX 0
#define INCLUDE_PROPERTY_ECGDATAURL 0
#define INCLUDE_PROPERTY_HASMEASURMENT 0
#define INCLUDE_PROPERTY_SENDALARM 0
#define INCLUDE_PROPERTY_HASDRUGTOMEDICINE 0
#define INCLUDE_PROPERTY_SPECIALLITY 0
#define INCLUDE_PROPERTY_ADVICETEXT 0
#define INCLUDE_PROPERTY_XPOINT 0
#define INCLUDE_PROPERTY_HASYAXIS 0
#define INCLUDE_PROPERTY_HASDRUGTOTAKE 0
#define INCLUDE_PROPERTY_HASMEDICALRECORDSCARD 0
#define INCLUDE_PROPERTY_HASACCESS 0
#define INCLUDE_PROPERTY_VENTICULARRATE 0
#define INCLUDE_PROPERTY_CONTAINECGSURVEYS 0
#define INCLUDE_PROPERTY_DRUGNAME 0
#define INCLUDE_PROPERTY_SENDADVICE 0
#define INCLUDE_PROPERTY_HASPWAVE 0
#define INCLUDE_PROPERTY_HASDOCUMENT 0
#define INCLUDE_PROPERTY_ISPATIENTMEDICINEADDICTED 0
#define INCLUDE_PROPERTY_SERVEYDATE 0
#define INCLUDE_PROPERTY_DATAVALUE 0
#define INCLUDE_PROPERTY_LEADDESCRIPTION 0
#define INCLUDE_PROPERTY_AGE 0
#define INCLUDE_PROPERTY_ALARMSTATUS 0
#define INCLUDE_PROPERTY_DRUGANNOTATION 0
#define INCLUDE_PROPERTY_PATIENTBLOODTYPE 0
#define INCLUDE_PROPERTY_PHARMNAME 0
#define INCLUDE_PROPERTY_ATRIALRYTHM 0
#define INCLUDE_PROPERTY_HASPERSLOCATION 0
#define INCLUDE_PROPERTY_PATIENTRHFACTOR 0
#define INCLUDE_PROPERTY_SURVEYECGINFO 0
#define INCLUDE_PROPERTY_CONTAINUSHSURVEYS 0
#define INCLUDE_PROPERTY_HASAMBLOCATION 0
#define INCLUDE_PROPERTY_DISEASEDESCRIPTION 0
#define INCLUDE_PROPERTY_HASDRUGTOSALE 0
#define INCLUDE_PROPERTY_SERVEYRESULT 0
#define INCLUDE_PROPERTY_PATIENTHEIGHT 0
#define INCLUDE_PROPERTY_HASLEAD 0
#define INCLUDE_PROPERTY_WORKHOSPITAL 0
#define INCLUDE_PROPERTY_ALARMTIME 0
#define INCLUDE_PROPERTY_PHONE 0
#define INCLUDE_PROPERTY_HASHOSPLOCATION 0
#define INCLUDE_PROPERTY_STARTTIME 0
#define INCLUDE_PROPERTY_HASHEARTRATE 0
#define INCLUDE_PROPERTY_HASTWAVE 0
#define INCLUDE_PROPERTY_MEASURMENTDESCRIPTION 0
#define INCLUDE_PROPERTY_HASPHARMLOCATION 0
#define INCLUDE_PROPERTY_MEASURMENTVALUE 0
#define INCLUDE_PROPERTY_SERVEYDATALINK 0
#define INCLUDE_PROPERTY_HASANOMALY 0
#define INCLUDE_PROPERTY_INTERVALSCALE 0
#define INCLUDE_PROPERTY_ISPATIENTSMOKE 0
#define INCLUDE_PROPERTY_HASXAXIS 0
#define INCLUDE_PROPERTY_HASPATIENTMETRICS 0
#define INCLUDE_PROPERTY_ENDWAVECOMP 0
#define INCLUDE_PROPERTY_DOSAGE 0
#define INCLUDE_PROPERTY_SERVEYTYPE 0
#define INCLUDE_PROPERTY_DOCUMENTNUMBERFULL 0
#define INCLUDE_PROPERTY_PEAK 0
#define INCLUDE_PROPERTY_LONG 0
#define INCLUDE_PROPERTY_ISPATIENTALCOHOLADDICTED 0
#define INCLUDE_PROPERTY_SERVEYDESCRIPTION 0
#define INCLUDE_PROPERTY_DOCUMENTTYPE 0
#define INCLUDE_PROPERTY_HASDIAGNOSIS 0
#define INCLUDE_PROPERTY_LAT 0
#define INCLUDE_PROPERTY_SURNAME 0
#define INCLUDE_PROPERTY_DOCUMENTRELEASEDATE 0
#define INCLUDE_PROPERTY_AUTHREQUESTSTATUS 0
#define INCLUDE_PROPERTY_PERSONINFORMATION 0
#define INCLUDE_PROPERTY_PASSWORD 0
#define INCLUDE_PROPERTY_MBOX 0
#define INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT 0
#define INCLUDE_PROPERTY_ATRIALRATE 0
#define INCLUDE_PROPERTY_WORKAMBULANCE 0
#define INCLUDE_PROPERTY_NAME 0
#define INCLUDE_PROPERTY_ENDTIME 0
#define INCLUDE_PROPERTY_ADVICETIME 0
#define INCLUDE_PROPERTY_HASWAVEFORMSTRUCTURE 0
#define INCLUDE_PROPERTY_HASWAVECOMPONENT 0
#define INCLUDE_PROPERTY_DISEASETYPE 0
#define INCLUDE_PROPERTY_SERVEYUSHINFO 0
#define INCLUDE_PROPERTY_CONTAINDISEASES 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_ALARM 0
#define INCLUDE_CLASS_DOCTOR 0
#define INCLUDE_CLASS_NURSE 0
#define INCLUDE_CLASS_ECGTWAVE 0
#define INCLUDE_CLASS_ECGDIAGNOSIS 0
#define INCLUDE_CLASS_LOCATION 0
#define INCLUDE_CLASS_ECGWAVECOMPONENT 0
#define INCLUDE_CLASS_ECGDATA 0
#define INCLUDE_CLASS_ADVICE 0
#define INCLUDE_CLASS_PATIENTMETRICS 0
#define INCLUDE_CLASS_MEDICALRECORDSCARD 0
#define INCLUDE_CLASS_PHARMACY 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_HOSPITAL 0
#define INCLUDE_CLASS_MEASURMENT 0
#define INCLUDE_CLASS_RHYTHM 0
#define INCLUDE_CLASS_PROFILE 0
#define INCLUDE_CLASS_SERVEY 0
#define INCLUDE_CLASS_DISEASE 0
#define INCLUDE_CLASS_ECGSERVEY 0
#define INCLUDE_CLASS_DOCUMENT 0
#define INCLUDE_CLASS_BED 0
#define INCLUDE_CLASS_ECGLEAD 0
#define INCLUDE_CLASS_ECGQRSCOMPLEX 0
#define INCLUDE_CLASS_PATIENTMAP 0
#define INCLUDE_CLASS_MEDIC 0
#define INCLUDE_CLASS_ANOMALY 0
#define INCLUDE_CLASS_USHSERVEY 0
#define INCLUDE_CLASS_CARING 0
#define INCLUDE_CLASS_AMBULANCE 0
#define INCLUDE_CLASS_CRITERIA 0
#define INCLUDE_CLASS_WAVEFORMSTRUCTURE 0
#define INCLUDE_CLASS_EQUIPMENT 0
#define INCLUDE_CLASS_DRUG 0
#define INCLUDE_CLASS_HEARTRATE 0
#define INCLUDE_CLASS_ECGXAXIS 0
#define INCLUDE_CLASS_ECGPWAVE 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_PATIENT 0
#define INCLUDE_CLASS_ECGYAXIS 0
#define INCLUDE_CLASS_AUTHREQUEST 0


#endif


#if INCLUDE_CLASS_THING
extern sslog_class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_ALARM
extern sslog_class_t *CLASS_ALARM;
#endif
#if INCLUDE_CLASS_DOCTOR
extern sslog_class_t *CLASS_DOCTOR;
#endif
#if INCLUDE_CLASS_NURSE
extern sslog_class_t *CLASS_NURSE;
#endif
#if INCLUDE_CLASS_ECGTWAVE
extern sslog_class_t *CLASS_ECGTWAVE;
#endif
#if INCLUDE_CLASS_ECGDIAGNOSIS
extern sslog_class_t *CLASS_ECGDIAGNOSIS;
#endif
#if INCLUDE_CLASS_LOCATION
extern sslog_class_t *CLASS_LOCATION;
#endif
#if INCLUDE_CLASS_ECGWAVECOMPONENT
extern sslog_class_t *CLASS_ECGWAVECOMPONENT;
#endif
#if INCLUDE_CLASS_ECGDATA
extern sslog_class_t *CLASS_ECGDATA;
#endif
#if INCLUDE_CLASS_ADVICE
extern sslog_class_t *CLASS_ADVICE;
#endif
#if INCLUDE_CLASS_PATIENTMETRICS
extern sslog_class_t *CLASS_PATIENTMETRICS;
#endif
#if INCLUDE_CLASS_MEDICALRECORDSCARD
extern sslog_class_t *CLASS_MEDICALRECORDSCARD;
#endif
#if INCLUDE_CLASS_PHARMACY
extern sslog_class_t *CLASS_PHARMACY;
#endif
#if INCLUDE_CLASS_NOTHING
extern sslog_class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_HOSPITAL
extern sslog_class_t *CLASS_HOSPITAL;
#endif
#if INCLUDE_CLASS_MEASURMENT
extern sslog_class_t *CLASS_MEASURMENT;
#endif
#if INCLUDE_CLASS_RHYTHM
extern sslog_class_t *CLASS_RHYTHM;
#endif
#if INCLUDE_CLASS_PROFILE
extern sslog_class_t *CLASS_PROFILE;
#endif
#if INCLUDE_CLASS_SERVEY
extern sslog_class_t *CLASS_SERVEY;
#endif
#if INCLUDE_CLASS_DISEASE
extern sslog_class_t *CLASS_DISEASE;
#endif
#if INCLUDE_CLASS_ECGSERVEY
extern sslog_class_t *CLASS_ECGSERVEY;
#endif
#if INCLUDE_CLASS_DOCUMENT
extern sslog_class_t *CLASS_DOCUMENT;
#endif
#if INCLUDE_CLASS_BED
extern sslog_class_t *CLASS_BED;
#endif
#if INCLUDE_CLASS_ECGLEAD
extern sslog_class_t *CLASS_ECGLEAD;
#endif
#if INCLUDE_CLASS_ECGQRSCOMPLEX
extern sslog_class_t *CLASS_ECGQRSCOMPLEX;
#endif
#if INCLUDE_CLASS_PATIENTMAP
extern sslog_class_t *CLASS_PATIENTMAP;
#endif
#if INCLUDE_CLASS_MEDIC
extern sslog_class_t *CLASS_MEDIC;
#endif
#if INCLUDE_CLASS_ANOMALY
extern sslog_class_t *CLASS_ANOMALY;
#endif
#if INCLUDE_CLASS_USHSERVEY
extern sslog_class_t *CLASS_USHSERVEY;
#endif
#if INCLUDE_CLASS_CARING
extern sslog_class_t *CLASS_CARING;
#endif
#if INCLUDE_CLASS_AMBULANCE
extern sslog_class_t *CLASS_AMBULANCE;
#endif
#if INCLUDE_CLASS_CRITERIA
extern sslog_class_t *CLASS_CRITERIA;
#endif
#if INCLUDE_CLASS_WAVEFORMSTRUCTURE
extern sslog_class_t *CLASS_WAVEFORMSTRUCTURE;
#endif
#if INCLUDE_CLASS_EQUIPMENT
extern sslog_class_t *CLASS_EQUIPMENT;
#endif
#if INCLUDE_CLASS_DRUG
extern sslog_class_t *CLASS_DRUG;
#endif
#if INCLUDE_CLASS_HEARTRATE
extern sslog_class_t *CLASS_HEARTRATE;
#endif
#if INCLUDE_CLASS_ECGXAXIS
extern sslog_class_t *CLASS_ECGXAXIS;
#endif
#if INCLUDE_CLASS_ECGPWAVE
extern sslog_class_t *CLASS_ECGPWAVE;
#endif
#if INCLUDE_CLASS_PERSON
extern sslog_class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_PATIENT
extern sslog_class_t *CLASS_PATIENT;
#endif
#if INCLUDE_CLASS_ECGYAXIS
extern sslog_class_t *CLASS_ECGYAXIS;
#endif
#if INCLUDE_CLASS_AUTHREQUEST
extern sslog_class_t *CLASS_AUTHREQUEST;
#endif


#if INCLUDE_PROPERTY_HASTHEARTRHYTHM
extern sslog_property_t *PROPERTY_HASTHEARTRHYTHM;
#endif
#if INCLUDE_PROPERTY_VENTICULARRYTHM
extern sslog_property_t *PROPERTY_VENTICULARRYTHM;
#endif
#if INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT
extern sslog_property_t *PROPERTY_HASSTATIONAREQUIPMENT;
#endif
#if INCLUDE_PROPERTY_TAKEDRUGTIME
extern sslog_property_t *PROPERTY_TAKEDRUGTIME;
#endif
#if INCLUDE_PROPERTY_HASPATIENTMAP
extern sslog_property_t *PROPERTY_HASPATIENTMAP;
#endif
#if INCLUDE_PROPERTY_RESPONSETOALARM
extern sslog_property_t *PROPERTY_RESPONSETOALARM;
#endif
#if INCLUDE_PROPERTY_ISPATIENTDRUGADDICTED
extern sslog_property_t *PROPERTY_ISPATIENTDRUGADDICTED;
#endif
#if INCLUDE_PROPERTY_STARTWAVECOMP
extern sslog_property_t *PROPERTY_STARTWAVECOMP;
#endif
#if INCLUDE_PROPERTY_USEEQUIPMENTTIME
extern sslog_property_t *PROPERTY_USEEQUIPMENTTIME;
#endif
#if INCLUDE_PROPERTY_USERNAME
extern sslog_property_t *PROPERTY_USERNAME;
#endif
#if INCLUDE_PROPERTY_ISONLINE
extern sslog_property_t *PROPERTY_ISONLINE;
#endif
#if INCLUDE_PROPERTY_HASCRITERIA
extern sslog_property_t *PROPERTY_HASCRITERIA;
#endif
#if INCLUDE_PROPERTY_FREEPATIENTCAPACITY
extern sslog_property_t *PROPERTY_FREEPATIENTCAPACITY;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOSAVE
extern sslog_property_t *PROPERTY_HASDRUGTOSAVE;
#endif
#if INCLUDE_PROPERTY_EQUIPPARAMETER
extern sslog_property_t *PROPERTY_EQUIPPARAMETER;
#endif
#if INCLUDE_PROPERTY_PATIENTWEIGHT
extern sslog_property_t *PROPERTY_PATIENTWEIGHT;
#endif
#if INCLUDE_PROPERTY_READYTOHELP
extern sslog_property_t *PROPERTY_READYTOHELP;
#endif
#if INCLUDE_PROPERTY_IMG
extern sslog_property_t *PROPERTY_IMG;
#endif
#if INCLUDE_PROPERTY_PASSAUTH
extern sslog_property_t *PROPERTY_PASSAUTH;
#endif
#if INCLUDE_PROPERTY_HOSPITALNAME
extern sslog_property_t *PROPERTY_HOSPITALNAME;
#endif
#if INCLUDE_PROPERTY_HASDOCTOR
extern sslog_property_t *PROPERTY_HASDOCTOR;
#endif
#if INCLUDE_PROPERTY_CARNUMBER
extern sslog_property_t *PROPERTY_CARNUMBER;
#endif
#if INCLUDE_PROPERTY_HASQRSCOMPLEX
extern sslog_property_t *PROPERTY_HASQRSCOMPLEX;
#endif
#if INCLUDE_PROPERTY_ECGDATAURL
extern sslog_property_t *PROPERTY_ECGDATAURL;
#endif
#if INCLUDE_PROPERTY_HASMEASURMENT
extern sslog_property_t *PROPERTY_HASMEASURMENT;
#endif
#if INCLUDE_PROPERTY_SENDALARM
extern sslog_property_t *PROPERTY_SENDALARM;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOMEDICINE
extern sslog_property_t *PROPERTY_HASDRUGTOMEDICINE;
#endif
#if INCLUDE_PROPERTY_SPECIALLITY
extern sslog_property_t *PROPERTY_SPECIALLITY;
#endif
#if INCLUDE_PROPERTY_ADVICETEXT
extern sslog_property_t *PROPERTY_ADVICETEXT;
#endif
#if INCLUDE_PROPERTY_XPOINT
extern sslog_property_t *PROPERTY_XPOINT;
#endif
#if INCLUDE_PROPERTY_HASYAXIS
extern sslog_property_t *PROPERTY_HASYAXIS;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOTAKE
extern sslog_property_t *PROPERTY_HASDRUGTOTAKE;
#endif
#if INCLUDE_PROPERTY_HASMEDICALRECORDSCARD
extern sslog_property_t *PROPERTY_HASMEDICALRECORDSCARD;
#endif
#if INCLUDE_PROPERTY_HASACCESS
extern sslog_property_t *PROPERTY_HASACCESS;
#endif
#if INCLUDE_PROPERTY_VENTICULARRATE
extern sslog_property_t *PROPERTY_VENTICULARRATE;
#endif
#if INCLUDE_PROPERTY_CONTAINECGSURVEYS
extern sslog_property_t *PROPERTY_CONTAINECGSURVEYS;
#endif
#if INCLUDE_PROPERTY_DRUGNAME
extern sslog_property_t *PROPERTY_DRUGNAME;
#endif
#if INCLUDE_PROPERTY_SENDADVICE
extern sslog_property_t *PROPERTY_SENDADVICE;
#endif
#if INCLUDE_PROPERTY_HASPWAVE
extern sslog_property_t *PROPERTY_HASPWAVE;
#endif
#if INCLUDE_PROPERTY_HASDOCUMENT
extern sslog_property_t *PROPERTY_HASDOCUMENT;
#endif
#if INCLUDE_PROPERTY_ISPATIENTMEDICINEADDICTED
extern sslog_property_t *PROPERTY_ISPATIENTMEDICINEADDICTED;
#endif
#if INCLUDE_PROPERTY_SERVEYDATE
extern sslog_property_t *PROPERTY_SERVEYDATE;
#endif
#if INCLUDE_PROPERTY_DATAVALUE
extern sslog_property_t *PROPERTY_DATAVALUE;
#endif
#if INCLUDE_PROPERTY_LEADDESCRIPTION
extern sslog_property_t *PROPERTY_LEADDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_AGE
extern sslog_property_t *PROPERTY_AGE;
#endif
#if INCLUDE_PROPERTY_ALARMSTATUS
extern sslog_property_t *PROPERTY_ALARMSTATUS;
#endif
#if INCLUDE_PROPERTY_DRUGANNOTATION
extern sslog_property_t *PROPERTY_DRUGANNOTATION;
#endif
#if INCLUDE_PROPERTY_PATIENTBLOODTYPE
extern sslog_property_t *PROPERTY_PATIENTBLOODTYPE;
#endif
#if INCLUDE_PROPERTY_PHARMNAME
extern sslog_property_t *PROPERTY_PHARMNAME;
#endif
#if INCLUDE_PROPERTY_ATRIALRYTHM
extern sslog_property_t *PROPERTY_ATRIALRYTHM;
#endif
#if INCLUDE_PROPERTY_HASPERSLOCATION
extern sslog_property_t *PROPERTY_HASPERSLOCATION;
#endif
#if INCLUDE_PROPERTY_PATIENTRHFACTOR
extern sslog_property_t *PROPERTY_PATIENTRHFACTOR;
#endif
#if INCLUDE_PROPERTY_SURVEYECGINFO
extern sslog_property_t *PROPERTY_SURVEYECGINFO;
#endif
#if INCLUDE_PROPERTY_CONTAINUSHSURVEYS
extern sslog_property_t *PROPERTY_CONTAINUSHSURVEYS;
#endif
#if INCLUDE_PROPERTY_HASAMBLOCATION
extern sslog_property_t *PROPERTY_HASAMBLOCATION;
#endif
#if INCLUDE_PROPERTY_DISEASEDESCRIPTION
extern sslog_property_t *PROPERTY_DISEASEDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOSALE
extern sslog_property_t *PROPERTY_HASDRUGTOSALE;
#endif
#if INCLUDE_PROPERTY_SERVEYRESULT
extern sslog_property_t *PROPERTY_SERVEYRESULT;
#endif
#if INCLUDE_PROPERTY_PATIENTHEIGHT
extern sslog_property_t *PROPERTY_PATIENTHEIGHT;
#endif
#if INCLUDE_PROPERTY_HASLEAD
extern sslog_property_t *PROPERTY_HASLEAD;
#endif
#if INCLUDE_PROPERTY_WORKHOSPITAL
extern sslog_property_t *PROPERTY_WORKHOSPITAL;
#endif
#if INCLUDE_PROPERTY_ALARMTIME
extern sslog_property_t *PROPERTY_ALARMTIME;
#endif
#if INCLUDE_PROPERTY_PHONE
extern sslog_property_t *PROPERTY_PHONE;
#endif
#if INCLUDE_PROPERTY_HASHOSPLOCATION
extern sslog_property_t *PROPERTY_HASHOSPLOCATION;
#endif
#if INCLUDE_PROPERTY_STARTTIME
extern sslog_property_t *PROPERTY_STARTTIME;
#endif
#if INCLUDE_PROPERTY_HASHEARTRATE
extern sslog_property_t *PROPERTY_HASHEARTRATE;
#endif
#if INCLUDE_PROPERTY_HASTWAVE
extern sslog_property_t *PROPERTY_HASTWAVE;
#endif
#if INCLUDE_PROPERTY_MEASURMENTDESCRIPTION
extern sslog_property_t *PROPERTY_MEASURMENTDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_HASPHARMLOCATION
extern sslog_property_t *PROPERTY_HASPHARMLOCATION;
#endif
#if INCLUDE_PROPERTY_MEASURMENTVALUE
extern sslog_property_t *PROPERTY_MEASURMENTVALUE;
#endif
#if INCLUDE_PROPERTY_SERVEYDATALINK
extern sslog_property_t *PROPERTY_SERVEYDATALINK;
#endif
#if INCLUDE_PROPERTY_HASANOMALY
extern sslog_property_t *PROPERTY_HASANOMALY;
#endif
#if INCLUDE_PROPERTY_INTERVALSCALE
extern sslog_property_t *PROPERTY_INTERVALSCALE;
#endif
#if INCLUDE_PROPERTY_ISPATIENTSMOKE
extern sslog_property_t *PROPERTY_ISPATIENTSMOKE;
#endif
#if INCLUDE_PROPERTY_HASXAXIS
extern sslog_property_t *PROPERTY_HASXAXIS;
#endif
#if INCLUDE_PROPERTY_HASPATIENTMETRICS
extern sslog_property_t *PROPERTY_HASPATIENTMETRICS;
#endif
#if INCLUDE_PROPERTY_ENDWAVECOMP
extern sslog_property_t *PROPERTY_ENDWAVECOMP;
#endif
#if INCLUDE_PROPERTY_DOSAGE
extern sslog_property_t *PROPERTY_DOSAGE;
#endif
#if INCLUDE_PROPERTY_SERVEYTYPE
extern sslog_property_t *PROPERTY_SERVEYTYPE;
#endif
#if INCLUDE_PROPERTY_DOCUMENTNUMBERFULL
extern sslog_property_t *PROPERTY_DOCUMENTNUMBERFULL;
#endif
#if INCLUDE_PROPERTY_PEAK
extern sslog_property_t *PROPERTY_PEAK;
#endif
#if INCLUDE_PROPERTY_LONG
extern sslog_property_t *PROPERTY_LONG;
#endif
#if INCLUDE_PROPERTY_ISPATIENTALCOHOLADDICTED
extern sslog_property_t *PROPERTY_ISPATIENTALCOHOLADDICTED;
#endif
#if INCLUDE_PROPERTY_SERVEYDESCRIPTION
extern sslog_property_t *PROPERTY_SERVEYDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_DOCUMENTTYPE
extern sslog_property_t *PROPERTY_DOCUMENTTYPE;
#endif
#if INCLUDE_PROPERTY_HASDIAGNOSIS
extern sslog_property_t *PROPERTY_HASDIAGNOSIS;
#endif
#if INCLUDE_PROPERTY_LAT
extern sslog_property_t *PROPERTY_LAT;
#endif
#if INCLUDE_PROPERTY_SURNAME
extern sslog_property_t *PROPERTY_SURNAME;
#endif
#if INCLUDE_PROPERTY_DOCUMENTRELEASEDATE
extern sslog_property_t *PROPERTY_DOCUMENTRELEASEDATE;
#endif
#if INCLUDE_PROPERTY_AUTHREQUESTSTATUS
extern sslog_property_t *PROPERTY_AUTHREQUESTSTATUS;
#endif
#if INCLUDE_PROPERTY_PERSONINFORMATION
extern sslog_property_t *PROPERTY_PERSONINFORMATION;
#endif
#if INCLUDE_PROPERTY_PASSWORD
extern sslog_property_t *PROPERTY_PASSWORD;
#endif
#if INCLUDE_PROPERTY_MBOX
extern sslog_property_t *PROPERTY_MBOX;
#endif
#if INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT
extern sslog_property_t *PROPERTY_HASPORTABLEEQUIPMENT;
#endif
#if INCLUDE_PROPERTY_ATRIALRATE
extern sslog_property_t *PROPERTY_ATRIALRATE;
#endif
#if INCLUDE_PROPERTY_WORKAMBULANCE
extern sslog_property_t *PROPERTY_WORKAMBULANCE;
#endif
#if INCLUDE_PROPERTY_NAME
extern sslog_property_t *PROPERTY_NAME;
#endif
#if INCLUDE_PROPERTY_ENDTIME
extern sslog_property_t *PROPERTY_ENDTIME;
#endif
#if INCLUDE_PROPERTY_ADVICETIME
extern sslog_property_t *PROPERTY_ADVICETIME;
#endif
#if INCLUDE_PROPERTY_HASWAVEFORMSTRUCTURE
extern sslog_property_t *PROPERTY_HASWAVEFORMSTRUCTURE;
#endif
#if INCLUDE_PROPERTY_HASWAVECOMPONENT
extern sslog_property_t *PROPERTY_HASWAVECOMPONENT;
#endif
#if INCLUDE_PROPERTY_DISEASETYPE
extern sslog_property_t *PROPERTY_DISEASETYPE;
#endif
#if INCLUDE_PROPERTY_SERVEYUSHINFO
extern sslog_property_t *PROPERTY_SERVEYUSHINFO;
#endif
#if INCLUDE_PROPERTY_CONTAINDISEASES
extern sslog_property_t *PROPERTY_CONTAINDISEASES;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
